#!/usr/bin/env zsh

() {
	local file
	for file in $(git diff --name-only --staged); do
		[[ -f $file ]] || continue

		cargo +nightly fmt --check -- "$file"
	done

	cargo clippy --fix --all-targets --allow-staged --allow-dirty --color='always'
	cargo test --color='always'
}
